### ISSUE TITLE
The app crashes when I try to change language 

### ISSUE THREAD

**Issue by chrisbarth01** [k3b/ToGoZip#18] opened 2019-05-28 12:17 UTC
#### Expected behavior 
I expected the app to change the language to the preferred language I selected. 

---

#### Actual behavior 
Each time I try to change the app's language, the app crashes. 

---

#### How to reproduce 
- Download, install and launch the latest version of the app
- Select storage location 
- Click on the first option (Language)
- Select any language (I selected French)
- Observe the crash.

---

Device: Gionee f100s 
Android version: v6.0
App version: v2.0.19.190413

---

#### Recording of the bug
- https://youtu.be/hNH-lI09GVE

---

**Comment by k3b** [comment] 2019-05-29 06:58
closed as duplicate of #20

**Closed by k3b** 2019-05-29 06:58 UTC
