### ISSUE TITLE
The app crashes when I click on the three dots at the top right corner of the screen 

### ISSUE THREAD

**Issue by chrisbarth01** [k3b/ToGoZip#19] opened 2019-05-28 12:32 UTC
#### Expected behavior 
I'm sort of new to the app so I expected a tab which may contain more features of the app to be displayed (when I click on the three dots at the top right corner of the screen).

---

#### Actual behavior 
Once I click on the three dots, the app crashed. 

---

#### How to reproduce 
- Download, install and launch the latest version of the app
- Select storage location 
- Click on the three vertically arranged dots
- Observe the crash.

---

Device: Gionee f100s 
Android version: v6.0
App version: v2.0.19.190413

---

#### Recording of the bug
- https://youtu.be/Jwe6rbS0ST4

---

**Comment by k3b** [comment] 2019-05-29 06:58
closed as duplicate of #20

**Closed by k3b** 2019-05-29 06:58 UTC
