### ISSUE TITLE
Settings may crash with NumberFormatException if number="" (i.e. after choosing language).

### ISSUE THREAD

**Issue by Sammaz2** [k3b/ToGoZip#10] opened 2018-05-17 00:41 UTC
### Actual behavior
I opened the app and then i clicked on edit after that i clicked on select which is at the bottom of the right corner. And then in Settings I clicked on output zip file, short text file in zip, long file:Min text Len and then in long text file in zip, options. In all the options i removed all the text and putted numbers. After that I clicked on language and choosed a language. Suddenly the app crashed. And then i tried to open the app again. But everytime it always crashed.

### How to reproduce

* First you need to download the app from fdroid and then install it. After that open the app.

* Click on the edit and then on select.

* After that in settings press on the output zip file, short text file in zip, long file:Min text Len. And remove the text and numbers.

* Then click on language and choose anyone. Suddenly the app will crash.

* After that try to open the app. But unfortunately you will not be able to open the app. As it always crashes. U have to uninstall it and then install it again.

https://youtu.be/GGREadbCDFk 

* Browser: ToGozip

* Version:2.0.12.180516

* Operating system:7.1.2

* Device model: Redmi 4

**Comment by k3b** [comment] 2018-05-17 13:27
Thans for reporting

the issue is reproducable.

If 

* you remove the number value from a number field "long File: Min Text Len"
* and then change the language 
* the settings activity is destroyed and then recreated with invalid number value
* ==> crash with number format exception.

In my opinion this is a minor so i will not create a hotfix release.

Will be fixed with the next release 2.0.13.

**Closed** 2018-11-02 23:49 UTC
Labels: bug
